Repository canonical/content-cache-operator, pull requests merged in 2024-12, with the labels that each got.

#5 Add support for tls-certificates integration
  charmcraft.yaml
  docs/changelog.md
  docs/how-to/enable-https.md
  docs/index.md
  docs/tutorial/quick-start.md
  lib/charms/tls_certificates_interface/v4/tls_certificates.py
  metadata.yaml
  requirements.txt
  src/certificates.py
  src/charm.py
  src/errors.py
  src/nginx_manager.py
  src/state.py
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/integration/test_charm.py
  tests/unit/test_charm.py
  tests/unit/test_nginx_manager.py
Labels: Libraries: OK

#10 Integration test using content-cache-backends-config charm
  .github/workflows/integration_test.yaml
  content-cache-backends-config/docs/changelog.md
  content-cache-backends-config/pyproject.toml
  content-cache-backends-config/src/state.py
  content-cache/docs/changelog.md
  content-cache/pyproject.toml
  content-cache/src/charm.py
  content-cache/tests/integration/conftest.py
  content-cache/tests/integration/helpers.py
  content-cache/tests/integration/test_charm.py
  content-cache/tests/integration/test_tls_cert.py
  content-cache/tests/unit/conftest.py
  content-cache/tests/unit/test_state.py
  content-cache/tests/unit/test_utilities.py
Labels: trivial

#14 Small changes to speed up local development
  content-cache/tests/conftest.py
  content-cache/tests/integration/conftest.py
Labels: trivial

#13 Add COS integration and metric logs
  .github/workflows/integration_test.yaml
  .licenserc.yaml
  content-cache/docs/changelog.md
  content-cache/docs/how-to/enable-cos.md
  content-cache/lib/charms/grafana_agent/v0/cos_agent.py
  content-cache/metadata.yaml
  content-cache/requirements.txt
  content-cache/src/charm.py
  content-cache/src/nginx_manager.py
  content-cache/src/state.py
  content-cache/tests/integration/conftest.py
  content-cache/tests/integration/helpers.py
  content-cache/tests/integration/test_basic.py
  content-cache/tests/integration/test_metric.py
  content-cache/tests/integration/test_tls_cert.py
  content-cache/tests/unit/requirements.txt
  content-cache/tests/unit/test_state.py
Labels: trivial

#16 Bug Fix: Nginx configuration conflict with multiple virtual hosts
  content-cache/docs/changelog.md
  content-cache/src/nginx_manager.py
  content-cache/tests/integration/conftest.py
  content-cache/tests/integration/helpers.py
  content-cache/tests/integration/test_basic.py
  content-cache/tests/unit/conftest.py
  content-cache/tests/unit/test_nginx_manager.py
Labels: bug, complex

#18 Update README.md
  content-cache-backends-config/README.md
  content-cache/README.md
Labels: documentation, trivial

#19 Add README in the root directory
  README.md
  content-cache/README.md
Labels: documentation, trivial

#21 Feature: Add juju unit name to the cache log name
  content-cache/src/charm.py
  content-cache/src/nginx_manager.py
  content-cache/tests/integration/test_metric.py
  content-cache/tests/unit/test_nginx_manager.py
Labels: complex
